name: senbonzakura
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  app_theme: 
    path: /home/maverick/Projects/legion/packages/app_theme
  appwrite: ^4.0.1
  auth_repository: 
    path: /home/maverick/Projects/legion/packages/auth_repository
  bloc: ^8.0.3
  connectivity_plus: ^2.2.1
  flex_color_scheme: ^5.0.0-dev.1
  # flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  fpdart: ^0.0.14
  freezed_annotation: ^1.1.0
  go_router: ^3.0.5
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  line_icons: ^2.0.1
  milky_way: 
    path: /home/maverick/Projects/legion/packages/milky_way
  path_provider: ^2.0.9
  q_form: 
    path: /home/maverick/Projects/legion/packages/q_form
  waterfall_flow: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.8
  change_app_package_name: ^1.0.0
  device_preview: ^1.0.0
  device_preview_screenshot: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  galaxy_lints: 
    path: /home/maverick/Projects/legion/packages/galaxy_lints
  json_serializable: ^6.1.5
  log_pose: 
    path: /home/maverick/Projects/legion/packages/log_pose


flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
